

name: CI
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
        ou1: ${{steps.step1.out1.test}}  
    steps:
      - id: step1
        run: echo "::set-output name=test::Hello"
    
    
  
    

   
