name: Greeting on variable day

on: [push]

env:
  DAY_OF_WEEK: Monday
  First_Name: Mona
  Greeting: Hello
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
          
